export type ConversationQualityMeta = {
  modelFinalize?: string;
  summaryCharCount?: number;
  sttSeconds?: number;
  sttModel?: string;
  sttResponseFormat?: string;
  sttRecoveryUsed?: boolean;
  sttAttemptCount?: number;
  sttSegmentCount?: number;
  sttSpeakerCount?: number;
  sttQualityWarnings?: string[];
  preprocessSeconds?: number;
  jobSecondsFinalize?: number;
  jobSecondsFormat?: number;
  llmApiCallsFinalize?: number;
  promptVersion?: string;
  generatedAt?: string;
  inputTokensEstimate?: number;
  outputTokensEstimate?: number;
  usedFallbackSummary?: boolean;
  errors?: string[];
};
