#!/usr/bin/env tsx

import { execFileSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadEnvFile } from "./lib/load-env-file";

function argValue(name: string) {
  const prefix = `--${name}=`;
  const direct = process.argv.find((arg) => arg.startsWith(prefix));
  if (direct) return direct.slice(prefix.length);
  const index = process.argv.findIndex((arg) => arg === `--${name}`);
  if (index >= 0) return process.argv[index + 1] ?? "";
  return "";
}

function readFirstEnv(names: string[]) {
  for (const name of names) {
    const value = process.env[name]?.trim();
    if (value) return value;
  }
  return "";
}

function requireEnv(names: string[], label?: string) {
  const value = readFirstEnv(names);
  if (value) return value;
  throw new Error(`${label ?? names.join(" / ")} が未設定です。`);
}

function quoteEnv(value: string) {
  return JSON.stringify(value);
}

function resolveWorkerImage() {
  const explicit = argValue("worker-image").trim() || readFirstEnv(["RUNPOD_WORKER_IMAGE", "DEFAULT_RUNPOD_WORKER_IMAGE"]);
  if (explicit) return explicit;

  const sha =
    readFirstEnv(["VERCEL_GIT_COMMIT_SHA", "GITHUB_SHA"]) ||
    execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim();
  if (!sha) {
    throw new Error("RUNPOD worker image を解決できません。--worker-image か RUNPOD_WORKER_IMAGE を指定してください。");
  }
  return `ghcr.io/mirr-luke/pararia-runpod-worker:sha-${sha}`;
}

async function main() {
  const envFile = argValue("env-file").trim();
  if (envFile) {
    await loadEnvFile(path.resolve(envFile), {
      optional: false,
      overrideExisting: false,
    });
  }

  const outputPath = path.resolve(
    argValue("output").trim() || ".tmp/.env.production.runpod"
  );
  const baseUrl =
    argValue("base-url").trim() ||
    readFirstEnv(["NEXT_PUBLIC_APP_URL", "NEXTAUTH_URL"]) ||
    "https://pararia.vercel.app";
  const maintenanceSecret = requireEnv(
    ["MAINTENANCE_SECRET", "CRON_SECRET", "MAINTENANCE_CRON_SECRET"],
    "maintenance secret"
  );
  const cronSecret = readFirstEnv(["CRON_SECRET", "MAINTENANCE_CRON_SECRET"]) || maintenanceSecret;
  const workerImage = resolveWorkerImage();

  const lines = [
    "# Generated by scripts/write-production-ops-env.ts",
    `DATABASE_URL=${quoteEnv(requireEnv(["DATABASE_URL"]))}`,
    `DIRECT_URL=${quoteEnv(requireEnv(["DIRECT_URL", "DATABASE_URL"]))}`,
    `BLOB_READ_WRITE_TOKEN=${quoteEnv(requireEnv(["BLOB_READ_WRITE_TOKEN"]))}`,
    `NEXTAUTH_URL=${quoteEnv(baseUrl)}`,
    `NEXT_PUBLIC_APP_URL=${quoteEnv(baseUrl)}`,
    `MAINTENANCE_SECRET=${quoteEnv(maintenanceSecret)}`,
    `CRON_SECRET=${quoteEnv(cronSecret)}`,
    `RUNPOD_API_KEY=${quoteEnv(requireEnv(["RUNPOD_API_KEY"]))}`,
    `RUNPOD_WORKER_NAME=${quoteEnv(readFirstEnv(["RUNPOD_WORKER_NAME"]) || "pararia-gpu-worker")}`,
    `RUNPOD_WORKER_IMAGE=${quoteEnv(workerImage)}`,
    `PARARIA_BACKGROUND_MODE=${quoteEnv(readFirstEnv(["PARARIA_BACKGROUND_MODE"]) || "external")}`,
    `PARARIA_AUDIO_STORAGE_MODE=${quoteEnv(readFirstEnv(["PARARIA_AUDIO_STORAGE_MODE"]) || "blob")}`,
    `PARARIA_AUDIO_BLOB_ACCESS=${quoteEnv(readFirstEnv(["PARARIA_AUDIO_BLOB_ACCESS"]) || "private")}`,
  ];

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, `${lines.join("\n")}\n`, "utf8");
  console.log(
    JSON.stringify(
      {
        outputPath,
        baseUrl,
        workerImage,
        workerName: readFirstEnv(["RUNPOD_WORKER_NAME"]) || "pararia-gpu-worker",
        maintenanceSecretSource:
          process.env.MAINTENANCE_SECRET?.trim()
            ? "MAINTENANCE_SECRET"
            : process.env.CRON_SECRET?.trim()
              ? "CRON_SECRET"
              : "MAINTENANCE_CRON_SECRET",
      },
      null,
      2
    )
  );
}

main().catch((error) => {
  console.error("[write-production-ops-env] fatal", error);
  process.exitCode = 1;
});
